<a href="https://colab.research.google.com/github/monikagulia1/IMPORTANT-LIBRARIES/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create an array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

# Create an array filled with zeros
arr = np.zeros(5)
print(arr)  # Output: [0. 0. 0. 0. 0.]

# Create an array filled with ones
arr = np.ones(5)
print(arr)  # Output: [1. 1. 1. 1. 1.]

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Access the element at index 3
print(arr[3])  # Output: 4

# Access the slice of elements from index 2 to 5
print(arr[2:5])  # Output: [3 4 5]

# Access the slice of elements from index 2 to 7 with step size 2
print(arr[2:7:2])  # Output: [3 5 7]

4
[3 4 5]
[3 5 7]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print(arr1 + arr2)  # Output: [5 7 9]

# Element-wise multiplication
print(arr1 * arr2)  # Output: [ 4 10 18]

[5 7 9]
[ 4 10 18]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
print(arr1 @ arr2)  # Output: [[19 22], [43 50]]

[[19 22]
 [43 50]]


In [ ]:
# Generate an array of 5 random numbers
arr = np.random.rand(5)
print(arr)

# Generate an array of 5 random numbers from a normal distribution
arr = np.random.randn(5)
print(arr)

# Generate an array of 5 random integers between 0 and 10
arr = np.random.randint(0, 10, 5)
print(arr)

# Generate an array of 5 random choices from the array [1, 2, 3, 4, 5]
arr = np.random.choice([1, 2, 3, 4, 5], 5)
print(arr)

[0.6450711  0.09078893 0.53778626 0.69091008 0.59365532]
[-1.29930286  2.18659209 -0.98756007 -0.50092735  1.06969734]
[4 9 3 1 1]
[2 1 1 1 4]


In [ ]:
arr = np.array([[1, 2], [3, 4]])

# Reshape the array to a 1D array
arr = np.reshape(arr, (4,))
print(arr)

# Transpose the array
arr = np.transpose(arr)
print(arr)

# Flatten the array
arr = arr.flatten() # removed arr from the arguments of flatten() method
print(arr)

# Concatenate two arrays
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr = np.concatenate((arr1, arr2))
print(arr)

# Split the array into two parts
arr = np.split(arr, 2)
print(arr)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[array([1, 2]), array([3, 4])]


In [ ]:
arr = np.array([3, 1, 2, 4])

# Find the indices of elements that are greater than 2
indices = np.where(arr > 2)
print(indices)

# Find the indices where elements should be inserted to maintain sorted order
indices = np.searchsorted(arr, [2.5, 3.5])
print(indices)

# Sort the array
arr = np.sort(arr)
print(arr)

# Return the indices that would sort the array
indices = np.argsort(arr)
print(indices)

(array([0, 3]),)
[3 3]
[1 2 3 4]
[0 1 2 3]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Calculate the minimum value
min_value = np.min(arr)
print(min_value)

# Calculate the maximum value
max_value = np.max(arr)
print(max_value)

# Calculate the mean
mean_value = np.mean(arr)
print(mean_value)

# Calculate the median
median_value = np.median(arr)
print(median_value)

# Calculate the standard deviation
std_dev = np.std(arr)
print(std_dev)

1
5
3.0
3.0
1.4142135623730951


In [ ]:
import numpy as np

# Create a matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Calculate the determinant of the matrix
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004


In [ ]:
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)

[-4.   4.5]


In [ ]:
# Calculate the eigenvalues and eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
rank_A = np.linalg.matrix_rank(A)
print(rank_A)

2


In [ ]:
# Calculate the power of the matrix
A_power = np.linalg.matrix_power(A, 2)
print(A_power)

[[ 7 10]
 [15 22]]
